services:
  #CAPA 1: Base de Datos (MongoDB)
  base-datos:
    image: mongo:latest
    container_name: mongodb-datos
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: mongosh --eval 'db.adminCommand(\"ping\")' --quiet 2> /dev/null || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  # CAPA 2: LÏgica de Negocio (Tu servidor Node de Ventas)
  servidor-app:
    build: .
    container_name: node-aplicacion
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      base-datos:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://base-datos:27017/mongodb-datos
    healthcheck:
      test: wget --spider -q -O - http://localhost:3000/api/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  mongo_data:
